steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/abi-martech-maz-mex/spotdemo', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/abi-martech-maz-mex/spotdemo']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'spotapi', '--image', 'gcr.io/abi-martech-maz-mex/spotdemo', '--region', 'us-central1']
images:
- gcr.io/abi-martech-maz-mex/spotdemo